[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dropper_giveaway = "7voKU6J5NiZ947AJjksL3WNRPQQC1TYUyatDai7TiGRH"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "./owner.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
