[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dropper_giveaway = "8s9yegeQK6UJPJq25jquj7vQQx6yJJtKZ7CFLjUaj5cL"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "mainnet"
wallet = "./owner.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
