[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dropper_giveaway = "EWExm3SZPzDMmGYDtszCpVZ2a8QoaVNSzVqkqDXhS8Kx"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "./owner.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
